version: '3'

services:
  api:
    image: ${TAG_NODE}:${VERSION:-latest}
    env_file: docker.env
    command: "npm run watch"
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    <% if (useMongoose || useMySQL) { %>links:<% } %><% if (useMongoose) { %>
      - mongo<% } %><% if (useMySQL) { %>
      - mysql<% } %>

  redis:
    image:  redis:4-alpine
    env_file: docker.env

  <% if (useMongoose) { %>mongo:
    image: mongo:3.4
    env_file: docker.env
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017<% } %>

  <% if (useMySQL) { %>mysql:
    image: mysql:5.7
    env_file: docker.env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 33060:3306<% } %>

<% if (useMongoose || useMySQL) { %>volumes:<% } %><% if (useMongoose) { %>
  mongodb:<% } %><% if (useMySQL) { %>
  mysql:<% } %>
